### ISSUE TITLE
按照文档接入，引入组件并使用，报错启动崩溃

### ISSUE THREAD

**Issue by zmm2tysu** [jd-antelope/tard#14]
版本： ^0.0.2-alpha.3

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/20849786/163954555-12b4d90b-8d75-4bdb-b6cd-a48a6b55eb71.png">

**Comment by zmm2tysu** [comment]
能更新下文档吗？  样式文件目录也不对啊

**Comment by huozhongyi123** [comment]
最新版本已修复问题，感谢反馈

**Comment by IOLOII** [comment]
> 能更新下文档吗？ 样式文件目录也不对啊

样式文件引入这样试下：
```ts
// .app.ts
import './app.less'
```
```less
// app.less
@import "~tard/dist/styles/index.less";
```
